#!/usr/bin/env python3
# coding:utf-8
import sys
import argparse
import urllib
from urllib.parse import urlparse, parse_qs
import getpass
import configparser
import urllib.parse

from auth.netlogin import Netlogin
from auth.service import Serv
import os
import pathlib
def argparser():
    conf = configparser.ConfigParser()
    confpath =os.path.dirname(__file__)
    
    if os.path.exists(os.path.join(pathlib.Path.home(),".config","yauth.conf")):
        conf.read(os.path.join(pathlib.Path.home(),".config","yauth.conf"))
    else:
        conf.read(os.path.join(confpath,"conf"))
    parser = argparse.ArgumentParser(
        description="登陆服务： 0.校园网 1.中国移动 2.中国联通 3.中国电信\n格式：\n登入：./netlogin -l -u 202222xxxxx -p password -i 0\n注销: ./netlogin -q\n"
    )
    parser.add_argument("-l", "--login", dest="login", action="store_true")
    parser.add_argument(
        "-u",
        "--user",
        dest="user",
        type=str,
        help="username, like xxxx",
        default=conf.get("USER","username"),
    )
    parser.add_argument(
        "-p",
        "--password",
        dest="password",
        type=str,
        default=conf.get("USER","password"),
        help="password, your ysu account password.",
    )
    parser.add_argument(
        "-i",
        "--isp",
        dest="isp",
        type=int,
        help="Your ISP server name, default choice is 中国电信[3]",
        default=3,
        choices=[0, 1, 2, 3],
    )

    parser.add_argument(
        "-q", "--quit", dest="quit", action="store_true", help="Exit ysu ISP server."
    )
    parser.add_argument(
        "-t",
        "--test",
        dest="check",
        action="store_true",
        help="Check if the user is logged in.",
    )
    parser.add_argument("-d", "--down", dest="down", action="store_true")
    args = parser.parse_args()
    args.conf = conf
    return args


if __name__ == "__main__":

    args = argparser()
    loger = Netlogin(args)
    serv = Serv(args)
    if args.login:
        if not args.password:
            args.password = getpass.getpass(f"Password of user {args.user}>\n")
            # input("Input your password>\n")
        state, info = loger.login(user=args.user, pwd=urllib.parse.quote(args.password), type=args.isp)
        if not state:
            print("Login failed.")
        else:
            print("Login successfully.")

    if args.quit:
        state, info = loger.logout()
        if state:
            print(info)
        else:
            print("出现错误!")
            print(info)
        sys.exit(0)

    if args.check:
        info, error = loger.tst_net()
        if error:
            print(
                "Logged!\nCurrent user is {}.\nIP is {}.\nISP is {}".format(
                    info["user"], info["ip"], info["isp"]
                )
            )
        else:
            print("Not Authorized.")
    if args.down:
        serv.down()
